name: stellartools-soroban-rpc

services:
  quickstart:
    stdin_open: true
    tty: true
    image: stellar/quickstart:latest
    ports:
      - "8000:8000"
    container_name: stellartools-soroban-quickstart
    command: --standalone --enable-soroban-rpc
    networks:
      - stellartools-soroban-network

  database:
    image: postgres:15
    container_name: stellartools-soroban-database
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
    volumes:
      - stellartools-soroban-database-data:/var/lib/postgresql/data
    networks:
      - stellartools-soroban-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  stellartools-soroban-network:
    driver: bridge

volumes:
  stellartools-soroban-database-data:
